jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      pass: postgres
      port: 5433
      dbname: jaffle_shop
      schema: dbt_alice
      threads: 1
